### ISSUE TITLE
v3.4.1 tag is missing

### ISSUE THREAD

**Issue by ptrm** [sass/node-sass-binaries#113]
To be able to download the binaries from behind a firewall, I'm depending on the `SASS_BINARY_SITE=https://github.com/sass/node-sass-binaries/raw` url prefix when running npm. There is no `v3.4.1` tag in the repo, so the url https://github.com/sass/node-sass-binaries/raw/v3.4.1/win32-x64-46_binding.node returns a 404. For `v3.4.0` everything works fine: https://github.com/sass/node-sass-binaries/raw/v3.4.0/win32-x64-46_binding.node

**Comment by xzyfer** [comment]
Do not mirror to this repo. We don't tag the current version until the next version is ready in case we need to make emergency changes. Why are you not using the GH release asset url?

**Comment by ptrm** [comment]
The version to be used is determined by npm (I have only `"gulp-sass": "^2.0.4"` in dependencies). The url prefix used is the only one that works in my workplace (release assets are on S3 which is inacessible as a whole).

The https://github.com/sass/node-sass/releases/download/v3.4.1/win32-x64-46_binding.node url indeed works fine outside firewalls. Maybe you know of any way to make the binary downloads work regardless of version tags, but bypassing Amazon S3? We can always shrinkwrap the sass dependency to a stable version, although it's a bit tough for everyday use.

**Comment by xzyfer** [comment]
I would suggest copying the assets on a local server within your firewall. That was the original intent behind `SASS_BINARY_SITE`. Alternative just let npm build the binary for you. If you're on osx or linux you should have python2 installed.
