### ISSUE TITLE
Missing `darwin-ia32-xx_binding.node` binaries

### ISSUE THREAD

**Issue by JKAussieSkater** [sass/node-sass-binaries#120]
Failing to install `node-sass` on Mac OS X (10.11 El Capitan) using node.js x86 architecture.

* I've tried to npm install `node-sass` [using x86 node](https://nodejs.org/download/release/v0.12.9/), it failed to install the node bindings (the `/node_modules/node-sass/vendor/` folder isn't created)
 * npm appears to be caught in a loop which never ends (so the installation is never truly completed, the process can only be aborted by the user)
* The [node-sass-binaries](https://github.com/sass/node-sass-binaries) are completely absent of a `darwin-ia32-11_binding.node`
* Running node-sass anyway produces the following errors in the console log:

```ShellSession
Error: The `libsass` binding was not found in ~/node_modules/node-sass/vendor/darwin-ia32-11/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
```
* Running `npm rebuild node-sass` creates the following errors in the console log:

```ShellSession
> node-sass@3.4.2 install ~/node_modules/node-sass
> node scripts/install.js

module.js:338
    throw err;
    ^
Error: Cannot find module 'generate-object-property'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (~/node_modules/node-sass/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/index.js:1:76)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild" "node-sass"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
```
----

## Problem
It seems that the node-sass developers expect all OS X node variants to be x64 . . .

However, some 3rd party web-development applications, like [Brackets.io](http://brackets.io/), operate on their own x86 version of node.js (including in Mac OS X). Without a **darwin-ia32** binding.node, `node-sass` fails to install or function on these 3rd party web-development applications (a major issue for OS X users).

## Solution
Please add the node-sass binaries for **darwin-ia32** architecture.

@jasonsanjose, How did you manage to aquire the [`/node-sass/vendor/darwin-ia32-11/binding.node`](https://github.com/jasonsanjose/brackets-sass/tree/master/node/2.0.3/node_modules/node-sass/vendor/darwin-ia32-11) for your Brackets Sass extension?

Note: Also reported [sass/node-sass Issue # 1370](https://github.com/sass/node-sass/issues/1370)

**Comment by nschonni** [comment]
Closing in favour of the issue in the main repo
