### ISSUE TITLE
Electron Support

### ISSUE THREAD

**Issue by stefanKuijers** [sass/node-sass-binaries#123]
I've been looking into getting node-sass to work with Electron and finally managed to do so with the help of [this answer](https://discuss.atom.io/t/cross-platform-sass-compilation-with-node-sass-libsass/26372). 

I would like to contribute to the main repository so that electron can be supported for node-sass out of the box but as I don't really know anything about appveyor and how this is setup yet I would first like to add the binaries that work to this repo so people can use this.

I have binaries for:
- win32-64x-47 node 5.1.1 for electron 0.36.10
- linux-64x-47 node 5.1.1 for electron 0.36.9 (can fix this for electron 0.36.10 as well)

Do you guys want them here? and how should I name them?

**Comment by xzyfer** [comment]
Unfortunately it's more complicated than just having a couple binaries. If
we're not able to automatically test and create the binaries for all the
supported node versions on our supported operating system and architectures
we cannot continue.

The best way forward would be for you to document step by step everything
that is needed to build these binaries. If we're able to so it in an
automated way then we can move forward.

**Comment by stefanKuijers** [comment]
Understood. I will do some further testing to make sure which steps are need and which are optional. and post the results in https://github.com/sass/node-sass/issues/1047
