### ISSUE TITLE
Node 6 bindings for x64-48

### ISSUE THREAD

**Issue by TheSavior** [sass/node-sass-binaries#128]
It looks like node6 (now released) requires bindings for x64-48

**Comment by JaLuxe** [comment]
I second this! Can't install node-sass as it fails downloading:

Cannot download "https://github.com/sass/node-sass/releases/download/v3.6.0/win32-x64-48_binding.node":

HTTP error 404 Not Found

**Comment by CrackerakiUA** [comment]
Can we have temp fix for this, so we can work under v6.0.0 version of node?

**Comment by TheSavior** [comment]
It looks like they just released a new version of node-sass that supports node 6: https://github.com/sass/node-sass/releases/tag/v3.6.0

**Comment by CrackerakiUA** [comment]
Yes, i am trying to install `https://github.com/sass/node-sass-middleware` and that try to download x64-48 version of node-sass which not exists.

**Comment by nschonni** [comment]
Node 6 is now supported with 3.7 https://github.com/sass/node-sass/issues/1504
