### ISSUE TITLE
Build io.js 1.3 binaries

### ISSUE THREAD

**Issue by F21** [sass/node-sass-binaries#43]
I am using io.js 1.3 on Windows 8.1 64-bit. Node-sass currently fails when installing because the binaries do not exist:

```Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/win32-x64-node-1.3/binding.node```

**Comment by am11** [comment]
This is fixed in node-sass. We will use new naming convention from vNext.
