### ISSUE TITLE
problem with npm install node-sass in Ubuntu: binaries not found

### ISSUE THREAD

**Issue by linuxonrails** [sass/node-sass-binaries#44]
npm install node-sass

> node-sass@2.0.1 install /home/davidm/trash/prueba/node_modules/node-sass
> node scripts/install.js

**Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/linux-ia32-node-0.13/binding.node**

> node-sass@2.0.1 postinstall /home/davidm/trash/prueba/node_modules/node-sass
> node scripts/build.js

module.js:338
    throw err;
          ^
Error: Cannot find module '/home/davidm/trash/prueba/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Build failed

**Comment by am11** [comment]
Are you sure it is looking for node v0.1**3** binary? Is it released already? 

For node.js, we only provide binaries for the latest stable (0.12) and the penultimate stable (0.10) version of node.js. Note that v0.11 was unstable branch.

**Comment by linuxonrails** [comment]
I'm sorry. v0.13 it is unstable (current master in https://github.com/joyent/node)
