### ISSUE TITLE
darwin with node v0.11

### ISSUE THREAD

**Issue by NKjoep** [sass/node-sass-binaries#57]
I don't know if this is the right place, however I just run:

```bash
npm install -g node-sass
```

and I get this:
```log
 ~/workspace/tmp ∫ npm install node-sass -g
/Users/andrea/.npm-local/bin/node-sass -> /Users/andrea/.npm-local/lib/node_modules/node-sass/bin/node-sass

> node-sass@2.1.1 install /Users/andrea/.npm-local/lib/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/darwin-x64-node-0.11/binding.node

```

The installation went ahead and everything seem fine.

**Comment by am11** [comment]
Node 0.11 is unstable node.js branch, which is now superseded by 0.12 branch. 

We do not provide binaries for unstable versions of node.js.

Solution: upgrade to node.js v0.12 (stable) or downgrade to v0.10.x (stable) version.
https://nodejs.org/
